<?php
/**
 * BuildResultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VisWiz\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VisWiz.io API Documentation
 *
 * The SDK allows you to query and create new projects, builds or images within the VisWiz service.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@viswiz.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VisWiz\SDK;

/**
 * BuildResultsTest Class Doc Comment
 *
 * @category    Class
 * @description The results of a build comparison
 * @package     VisWiz\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BuildResultsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BuildResults"
     */
    public function testBuildResults()
    {
    }

    /**
     * Test attribute "build"
     */
    public function testPropertyBuild()
    {
    }

    /**
     * Test attribute "comparisonBuild"
     */
    public function testPropertyComparisonBuild()
    {
    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {
    }
}
